### PR TITLE
refactored semaphore-related code

### LINKED ISSUE #47: Create a private semaphore set.
In this piece of code `"."` is passed to `ftok()` function to create a key for the semaphore set:
https://github.com/v-zhuravlev/libzbxmodbus/blob/cf261eae6e6f63f886fa37fbeb663879d15bbc8b/src/modbus.c#L714-L721

A predetermined IPC resource key is typically used so that several _standalone_ applications can access them for synchronization and data exchange. In our case semaphore set is used by forks of the same process and no external process is expected to take part in the operation. For this we can pass `IPC_PRIVATE` as `key` parameter to `semget()` call and it will always create a new semaphore set exclusively for us.

As a result:
* there is no need to handle the case when semaphore set with a given key has already been created;
* no risk of conflict between different instances of the module or with external applications using same key by accident.

I would also suggest moving semaphore-related code into a separate source file.

### PR DESCRIPTION
**Pull request by i-ky**
Should resolve #47:
* moved semaphore-related code into separate source file;
* changed semaphore set creation to use `IPC_PRIVATE`;
* improved error messages.

### CODE REVIEW

**Comment by v-zhuravlev** [comment]
Would that be hard to develop a simple test to check that port locking is happening? This thing is complex (for me at least) and it would be good to keep under control.

**Comment by i-ky** [comment]
Do you want a synthetic test or close to real life scenario? If you know which ill effects the absence of locking can have, then we can try to reproduce these effects in tests.

**Comment by v-zhuravlev** [comment]
When locking is in place - another zabbix process must wait for the first process to finish in order to access the port(resource). Not sure how to test at this point. Ill effects are unpredictable - could be CRC errors, spontaneous timeouts...

**Comment by i-ky** [comment]
As I understand, the reason of ill effects is that multiple processes can simultaneously write to the same serial port. But it is difficult to guarantee that, because processes belong to Zabbix and actual writing is done by libmodbus. Even without locking the chance of getting any issues is small provided the number of parallel processes is low and port throughput is high. Making a real-life-like test which will 100% fail if there is something wrong with locking mechanism is quite challenging. We will need:
* lots of Zabbix processes;
* lots of parallel requests to the same port;
* simulate a really slow serial port.

Is it possible and is it worth it?

**Comment by v-zhuravlev** [comment]
>Even without locking the chance of getting any issues is small provided the number of parallel processes is low and port throughput is high
In real life it just doesn't work without locking - you would get errors all the time. 

I was thinking about some simple test(maybe unit level not integrational like we did befie) to test that locking is happening.

**Comment by i-ky** [comment]
Depends on #54.

**Pull request merged**
