### PR TITLE
Eliminate "Cannot read so much at once." error

### LINKED ISSUE #65: Cannot read so much data at once
Hi,

I am trying to read two Uint64 registers from a device, one at register 30513 and second is at 30775. Because they are very far from each others it returns "Cannot read so much data at once". I see in the code that you wanted to update this part. Any chance you are going to look at this in the nearest future?
This is a very important feature for my case - as I am connecting to a very old device, which has unstable connection, refuses connection every other time. So i get reasonable history on one metric and almost no data on the other.

### PR DESCRIPTION
**Pull request by i-ky**
…by dynamic allocation of read buffer. Closes #65.

@v-zhuravlev, please review.

@turkertopal, would be nice if you could test it.

### CODE REVIEW

**Comment by turkertopal** [comment]
@i-ky thank you for updating the code and sorry it took me a while to get back, i needed our devops to update test environment. result of update is it will read up to 116 skips. Which unfortunately doesn't allow me to read registers 30513 and 30775.

**Comment by i-ky** [comment]
@turkertopal, sounds like a really weird limitation. What is the key you use? What is the error you get if you try to read more than 116 `skip`s?

**Comment by turkertopal** [comment]
@i-ky log: 

 [root@4595fa9de8eb zabbix]# zabbix_get -s 127.0.0.1 -p 10050 -k "modbus_read[x.x.x.x,1,30513,3,I+130*skip+I]"
 ZBX_NOTSUPPORTED: Too many data
________________________________

**Comment by i-ky** [comment]
This [error comes from libmodbus](https://github.com/stephane/libmodbus/blob/820e15fada3e6983254a9de2b7ee2ea367e53116/src/modbus.c#L73) and it [references Modbus protocol specification](https://github.com/stephane/libmodbus/blob/820e15fada3e6983254a9de2b7ee2ea367e53116/src/modbus.h#L76-L94) as a source of these limitations. I guess module will have to read larger amount of registers in chunks.

**Pull request merged**
